#!/bin/sh -e

# walter: a deployment pipeline template
# Copyright (C) 2014 Recruit Technologies Co., Ltd. and contributors
# (see CONTRIBUTORS.md)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ! -h gopath/src/github.com/recruit-tech/walter ]; then
    mkdir -p gopath/src/github.com/recruit-tech/
    ln -s ../../../.. gopath/src/github.com/recruit-tech/walter
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GOFMTPATH=" ./stages ./engine ./config ./pipelines ./walter"

if ! [ -e $GOBIN/godep ]; then
    go get github.com/tools/godep
fi

$GOBIN/godep restore

# Don't surprise user by formatting their codes by stealth
if [ "--fmt" = "$1" ]; then
    gofmt -s -w -l $GOFMTPATH
fi

go install github.com/recruit-tech/walter
