#!/bin/sh -e

git submodule init && git submodule update

if [ ! -h gopath/src/github.com/recruit-tech/plumber ]; then
    mkdir -p gopath/src/github.com/recruit-tech/
    ln -s ../../../.. gopath/src/github.com/recruit-tech/plumber
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GOFMTPATH=" ./stages ./engine ./config ./pipelines ./plumber"

# Don't surprise user by formatting their codes by stealth
if [ "--fmt" = "$1" ]; then
    gofmt -s -w -l $GOFMTPATH
fi

go install github.com/recruit-tech/plumber
